# -*- coding: utf-8 -*-
"""Resume-Parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v8T1xcnDfVQNd8rWlZp54b5IncWmkRV4
"""

!pip install python-docx

!pip install nltk

import nltk
nltk.download('stopwords')

!pip install docx

!pip install pyresparser

from pyresparser import ResumeParser

import os
from docx import Document
import random

filed=input()

try:
    doc = Document()
    with open(filed, 'r') as file:
        doc.add_paragraph(file.read())
    doc.save("text.docx")
    data = ResumeParser('text.docx').get_extracted_data()
    
except:
    data = ResumeParser(filed).get_extracted_data()
    l=len(data['experience'])
    print(data['experience'])
    le=len(data['skills'])
    if(le<10):
      print("Score based on skills=",le*(random.randrange(8,10)))
    else:
      print("Score based on skills=",random.randrange(90, 99))